LIMIT_MAX_LENGTH_OF_ID_FIELD = 50
LIMIT_MAX_NUMBER_OF_FIELDS = 100
LIMIT_MAX_LENGTH_OF_DESCRIPTION = 2000
LIMIT_MAX_LENGTH_OF_NAME = 100
LIMIT_MAX_NUMBER_OF_ARMS = 10
LIMIT_MAX_LENGTH_OF_PARTICIPANT_ID_FIELD = 1000
LIMIT_MAX_NUMBER_OF_FILTERS = 20
