import json

from xngin.cli.main import export_openapi_spec


def test_openapi_endpoint_matches_cli_export(client, tmp_path):
    """The /openapi.json endpoint and the export-openapi-spec CLI must emit the same schema.

    They build the FastAPI app via different paths (the apiserver's configured app vs. a fresh app
    the CLI assembles), so this guards against the two drifting -- e.g. the CLI omitting
    generate_unique_id_function and regressing operationIds and response-model titles to FastAPI's
    autogenerated names.
    """
    endpoint_schema = client.get("/openapi.json").json()

    output = tmp_path / "openapi.json"
    export_openapi_spec(output)
    exported_schema = json.loads(output.read_text())

    assert endpoint_schema == exported_schema
