# This file was generated by tools/generate_wide_dwh.py
"""Definitions for the wide (500-column) testing data warehouse.

WIDE_DWH_RAW_DATA is the path to the compressed raw wide dwh data.
WIDE_DWH_PARTICIPANT_DEF is defined with respect to these contents and has
fields that map to our wide test dwh, covering all supported data types.
"""

from pathlib import Path

from xngin.apiserver.dwh.inspection_types import FieldDescriptor
from xngin.apiserver.routers.common_enums import DataType
from xngin.apiserver.settings import ParticipantsDef

WIDE_DWH_RAW_DATA = Path(__file__).resolve().parent.parent / "testdata/wide_dwh.csv.zst"

WIDE_DWH_PARTICIPANT_DEF = ParticipantsDef(
    type="schema",
    participant_type="wide_test_participant_type",
    table_name="wide_dwh",
    fields=[
        FieldDescriptor(field_name="id", data_type=DataType.BIGINT, is_unique_id=True),
        FieldDescriptor(field_name="participant_uuid", data_type=DataType.UUID),
        FieldDescriptor(field_name="age", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True),
        FieldDescriptor(
            field_name="gender", data_type=DataType.CHARACTER_VARYING, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="country_code",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="region", data_type=DataType.CHARACTER_VARYING, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="city", data_type=DataType.CHARACTER_VARYING, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="postal_code",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="registration_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(field_name="registration_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(
            field_name="language_code",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="education_level",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="marital_status",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="birth_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="is_active", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="is_verified", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="is_premium", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="is_internal", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="account_type",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="acquisition_channel",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="platform", data_type=DataType.CHARACTER_VARYING, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="device_type",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="browser_family",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="os_family", data_type=DataType.CHARACTER_VARYING, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="household_size", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_children", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="employment_status",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="industry_sector",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="years_as_customer", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="referral_source_id", data_type=DataType.BIGINT, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_01", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_02", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_03", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_04", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_05", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_06", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_07", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_08", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_09", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_10", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_11", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="demographic_flag_12", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="household_income", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="credit_score", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="savings_balance", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="checking_balance", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="total_debt", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="debt_to_income_ratio",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="annual_spend", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="avg_transaction_value",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_transactions_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_transactions_90d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="monthly_spend_m01", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m02", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m03", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m04", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m05", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m06", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m07", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m08", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m09", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m10", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m11", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="monthly_spend_m12", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="total_lifetime_value",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="avg_order_value", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_refunds", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="refund_amount_total", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="payment_method_primary",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="has_subscription", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="subscription_tier",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="subscription_monthly_fee",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="first_purchase_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="last_purchase_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="days_since_last_purchase",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="investment_portfolio_value",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="mortgage_balance", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="auto_loan_balance", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="student_loan_balance",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="insurance_premium_monthly",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="tax_bracket",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_credit_cards", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="credit_utilization_ratio",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="financial_metric_01", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_02", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_03", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_04", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_05", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_06", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_07", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_08", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_09", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="financial_metric_10", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_logins_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_logins_90d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="days_since_last_login",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="total_session_duration_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="avg_session_duration_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_sessions_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_pages_viewed_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_actions_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(field_name="last_login_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(field_name="first_login_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_search_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_checkout_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_profile_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_settings_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_help_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_notifications_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_dashboard_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_reports_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_export_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="pct_sessions_with_feature_share_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_search_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_checkout_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_profile_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_settings_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_help_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_notifications_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_dashboard_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_reports_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_export_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_uses_feature_share_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="weekly_active_w01", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w02", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w03", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w04", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w05", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w06", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w07", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w08", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w09", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="weekly_active_w10", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="bounce_rate_30d", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="click_through_rate_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="scroll_depth_avg", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_errors_encountered_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_support_tickets_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_feedback_submitted",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="nps_score", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="satisfaction_score", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="engagement_score_d01",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d02",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d03",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d04",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d05",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d06",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d07",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d08",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d09",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_score_d10",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w01",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w02",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w03",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w04",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w05",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w06",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w07",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w08",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w09",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="engagement_count_w10",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="avg_time_between_sessions_hrs",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="max_session_duration_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_unique_pages_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_downloads_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_uploads_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_shares_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_comments_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_likes_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_bookmarks_30d", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="has_completed_onboarding",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="onboarding_completion_date",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_notifications_sent_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_notifications_opened_30d",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="notification_click_rate",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="email_open_rate_30d", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="email_click_rate_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_social_connections",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="has_profile_photo", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="profile_completeness_pct",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_saved_items", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_wishlists", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="behavior_flag_01", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="behavior_flag_02", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="behavior_flag_03", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="behavior_flag_04", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="behavior_flag_05", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="behavior_flag_06", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="behavior_flag_07", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="behavior_flag_08", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="converted", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_clicks", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_impressions", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="revenue_7d", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="revenue_30d", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="revenue_90d", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="predicted_retention_days",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="churn_probability", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(field_name="conversion_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(
            field_name="conversion_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_retention_w01",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w02",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w03",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w04",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w05",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w06",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w07",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w08",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w09",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_retention_w10",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="metric_revenue_w01", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w02", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w03", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w04", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w05", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w06", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w07", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w08", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w09", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="metric_revenue_w10", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="first_conversion_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="num_conversions_total",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="conversion_value_total",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="time_to_convert_hours",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="goal_completion_rate",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_clicks_variant_1",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_views_variant_1",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_conversions_variant_1",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_revenue_variant_1",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_clicks_variant_2",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_views_variant_2",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_conversions_variant_2",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_revenue_variant_2",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_clicks_variant_3",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_views_variant_3",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_conversions_variant_3",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_revenue_variant_3",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_clicks_variant_4",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_views_variant_4",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_conversions_variant_4",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_revenue_variant_4",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_clicks_variant_5",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_views_variant_5",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_conversions_variant_5",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_revenue_variant_5",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="outcome_flag_01", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_02", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_03", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_04", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_05", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_06", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_07", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_08", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_09", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_10", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_11", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_12", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_13", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_14", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="outcome_flag_15", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="engagement_lift_pct", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="revenue_lift_pct", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="retention_lift_pct", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="activation_score", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="days_to_first_action",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="num_goal_completions",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="avg_order_frequency_30d",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="customer_effort_score",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="page_load_time_avg_ms",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="interaction_depth_score",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="repeat_visit_rate", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="viral_coefficient", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="treatment_group_primary",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="treatment_group_secondary",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="assignment_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(field_name="assignment_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(
            field_name="assignment_method",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="randomization_seed", data_type=DataType.BIGINT, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_001",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_001",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_001",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_002",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_002",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_002",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_003",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_003",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_003",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_004",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_004",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_004",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_005",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_005",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_005",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_006",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_006",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_006",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_007",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_007",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_007",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_008",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_008",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_008",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_009",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_009",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_009",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_arm_exp_010",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_exp_010",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_enrolled_date_exp_010",
            data_type=DataType.DATE,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="is_holdout", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="holdout_group_id", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="assignment_weight", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="stratification_bucket",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="consent_to_experiment",
            data_type=DataType.BOOLEAN,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_cohort",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_start_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="experiment_end_date", data_type=DataType.DATE, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="experiment_duration_days",
            data_type=DataType.INTEGER,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="assignment_confidence",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="is_eligible", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="eligibility_reason",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="experiment_priority", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="assignment_version", data_type=DataType.INTEGER, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="propensity_score_purchase",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="propensity_score_churn",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="propensity_score_upgrade",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="propensity_score_downgrade",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="propensity_score_referral",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="propensity_score_support_contact",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="propensity_score_return_visit",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="propensity_score_high_value",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="risk_score_credit", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="risk_score_fraud", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="risk_score_attrition",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="risk_score_default", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="risk_score_late_payment",
            data_type=DataType.NUMERIC,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_numeric_001", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_002", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_003", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_004", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_005", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_006", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_007", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_008", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_009", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_010", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_011", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_012", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_013", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_014", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_015", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_016", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_017", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_018", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_019", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_numeric_020", data_type=DataType.NUMERIC, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_categorical_001",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_002",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_003",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_004",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_005",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_006",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_007",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_008",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_009",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_categorical_010",
            data_type=DataType.CHARACTER_VARYING,
            is_filter=True,
            is_metric=True,
            is_strata=True,
        ),
        FieldDescriptor(
            field_name="feature_binary_001", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_binary_002", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_binary_003", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_binary_004", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_binary_005", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_binary_006", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_binary_007", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(
            field_name="feature_binary_008", data_type=DataType.BOOLEAN, is_filter=True, is_metric=True, is_strata=True
        ),
        FieldDescriptor(field_name="feature_binary_009", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="feature_binary_010", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="model_version", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="model_score_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(field_name="model_confidence", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="embedding_dim_001", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_002", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_003", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_004", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_005", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_006", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_007", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_008", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_009", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="embedding_dim_010", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="model_feature_interaction_01", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="model_feature_interaction_02", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="model_feature_interaction_03", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="model_feature_interaction_04", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="model_feature_interaction_05", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="prediction_date", data_type=DataType.DATE),
        FieldDescriptor(field_name="model_segment", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="anomaly_score", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="cluster_id", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="nearest_neighbor_distance", data_type=DataType.DOUBLE_PRECISION),
        FieldDescriptor(field_name="feature_importance_rank", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="model_calibration_score", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d01", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d02", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d03", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d04", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d05", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d06", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d07", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d08", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d09", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_daily_d10", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_count_daily_d01", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d02", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d03", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d04", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d05", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d06", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d07", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d08", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d09", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_daily_d10", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w01", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w02", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w03", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w04", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w05", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w06", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w07", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w08", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w09", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_count_weekly_w10", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="ts_value_weekly_w01", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w02", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w03", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w04", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w05", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w06", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w07", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w08", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w09", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_value_weekly_w10", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="trend_indicator_m01", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m02", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m03", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m04", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m05", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m06", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m07", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m08", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m09", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="trend_indicator_m10", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="ts_avg_monthly_m01", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m02", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m03", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m04", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m05", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m06", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m07", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m08", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m09", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="ts_avg_monthly_m10", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="seasonal_index_q1", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="seasonal_index_q2", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="seasonal_index_q3", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="seasonal_index_q4", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="rolling_avg_01w", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="rolling_avg_02w", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="rolling_avg_03w", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="rolling_avg_04w", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="rolling_avg_05w", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="rolling_avg_06w", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="yoy_growth_m01", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="yoy_growth_m02", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="yoy_growth_m03", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="yoy_growth_m04", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="yoy_growth_m05", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="yoy_growth_m06", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="momentum_indicator_m01", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="momentum_indicator_m02", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="momentum_indicator_m03", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="momentum_indicator_m04", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="source_system", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="audit_trail_uuid", data_type=DataType.UUID),
        FieldDescriptor(field_name="last_updated_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(field_name="created_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(field_name="etl_batch_id", data_type=DataType.BIGINT),
        FieldDescriptor(field_name="data_quality_score", data_type=DataType.NUMERIC),
        FieldDescriptor(field_name="metadata_version", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="is_test_record", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="record_status", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="consent_given", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="consent_date", data_type=DataType.DATE),
        FieldDescriptor(field_name="privacy_level", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="data_source_version", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="ingestion_timestamp", data_type=DataType.TIMESTAMP_WITH_TIMEZONE),
        FieldDescriptor(field_name="row_hash", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="partition_key", data_type=DataType.INTEGER),
        FieldDescriptor(field_name="processing_flag", data_type=DataType.BOOLEAN),
        FieldDescriptor(field_name="notes", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="tag_primary", data_type=DataType.CHARACTER_VARYING),
        FieldDescriptor(field_name="tag_secondary", data_type=DataType.CHARACTER_VARYING),
    ],
)
