from typing import Annotated

from pydantic import BaseModel, Field


class CallbackResponse(BaseModel):
    """The credentials returned to the SPA."""

    id_token: Annotated[
        str,
        Field(
            ...,
            description="The ID token as generated by Google. Represents a successful authentication.",
        ),
    ]
