from typing import Annotated

from pydantic import BaseModel, Field


class CallbackResponse(BaseModel):
    """The credentials returned to the SPA in exchange for a successful OIDC PKCE exchange.

    TODO: This is a placeholder for a longer-lived IDP-versatile session token.
    """

    id_token: Annotated[
        str,
        Field(
            ...,
            description="The ID token as generated by Google. Represents a successful authentication.",
        ),
    ]


class CallerIdentity(BaseModel):
    """Describes the user's identity in a format suitable for use in the frontend."""

    email: str
    iss: str  # issuer
    sub: str  # subject identifier
    hd: str  # hosted domain
    is_privileged: bool
