import warnings

# Workaround for: https://github.com/fastapi/fastapi/discussions/10537
warnings.filterwarnings(  # noqa: RUF067
    "ignore",
    message="`example`",
    category=DeprecationWarning,
    module="xngin.apiserver.main",
)

# Silence warnings generated by google-cloud-bigquery about an optional dependency: google-cloud-bigquery-storage is
# an optional dependency.
# https://github.com/googleapis/python-bigquery/blob/main/pyproject.toml
warnings.filterwarnings(  # noqa: RUF067
    action="ignore",
    message="Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.",
    category=UserWarning,
    module="google.cloud.bigquery.client",
)
