GET http://localhost:8000/strata?group=sample_group
Config-ID: testing
HTTP 200
```json
[
  {
    "table_name": "sample_group",
    "data_type": "double precision",
    "column_name": "baseline_income",
    "description": "",
    "strata_group": "",
    "strata_default": false,
    "id": "baseline_income"
  },
  {
    "table_name": "sample_group",
    "data_type": "double precision",
    "column_name": "current_income",
    "description": "",
    "strata_group": "",
    "strata_default": false,
    "id": "current_income"
  },
  {
    "table_name": "sample_group",
    "data_type": "integer",
    "column_name": "is_engaged",
    "description": "",
    "strata_group": "",
    "strata_default": false,
    "id": "is_engaged"
  },
  {
    "table_name": "sample_group",
    "data_type": "integer",
    "column_name": "is_onboarded",
    "description": "",
    "strata_group": "",
    "strata_default": false,
    "id": "is_onboarded"
  },
  {
    "table_name": "sample_group",
    "data_type": "integer",
    "column_name": "is_recruited",
    "description": "",
    "strata_group": "",
    "strata_default": false,
    "id": "is_recruited"
  },
  {
    "table_name": "sample_group",
    "data_type": "integer",
    "column_name": "is_registered",
    "description": "",
    "strata_group": "",
    "strata_default": false,
    "id": "is_registered"
  },
  {
    "table_name": "sample_group",
    "data_type": "integer",
    "column_name": "is_retained",
    "description": "",
    "strata_group": "",
    "strata_default": false,
    "id": "is_retained"
  }
]
```
