GET http://localhost:8000/strata?group=sample_group
Config-ID: testing
HTTP 200
```json
[
  {
    "data_type": "double precision",
    "column_name": "baseline_income",
    "description": "",
    "strata_group": ""
  },
  {
    "data_type": "double precision",
    "column_name": "current_income",
    "description": "",
    "strata_group": ""
  },
  {
    "data_type": "character varying",
    "column_name": "ethnicity",
    "description": "",
    "strata_group": "TODO"
  },
  {
    "data_type": "character varying",
    "column_name": "gender",
    "description": "",
    "strata_group": "TODO"
  },
  {
    "data_type": "integer",
    "column_name": "is_engaged",
    "description": "",
    "strata_group": ""
  },
  {
    "data_type": "integer",
    "column_name": "is_onboarded",
    "description": "",
    "strata_group": ""
  },
  {
    "data_type": "integer",
    "column_name": "is_recruited",
    "description": "",
    "strata_group": ""
  },
  {
    "data_type": "integer",
    "column_name": "is_registered",
    "description": "",
    "strata_group": ""
  },
  {
    "data_type": "integer",
    "column_name": "is_retained",
    "description": "",
    "strata_group": ""
  }
]
```
