-- Clustered test data schema for cluster randomization testing
-- Generated by tools/generate_clustered_data.py

CREATE TABLE {{table_name}} (
    participant_id BIGINT PRIMARY KEY NOT NULL,

    -- Three independent clustering schemes
    cluster_equal INTEGER NOT NULL,      -- Equal-sized clusters (CV ≈ 0)
    cluster_moderate INTEGER NOT NULL,   -- Moderate variation (CV ≈ 0.3)
    cluster_powerlaw INTEGER NOT NULL,   -- Power-law distribution (CV ≈ 3)

    -- Continuous outcomes
    income DECIMAL,                      -- Low ICC (0.05) with cluster_equal
    test_score DECIMAL,                  -- High ICC (0.20) with cluster_powerlaw

    -- Binary outcomes
    converted BOOLEAN,                   -- Low ICC (0.03) with cluster_moderate
    engaged BOOLEAN                      -- High ICC (0.15) with cluster_powerlaw
);

-- Indexes for efficient querying
CREATE INDEX idx_cluster_equal ON {{table_name}}(cluster_equal);
CREATE INDEX idx_cluster_moderate ON {{table_name}}(cluster_moderate);
CREATE INDEX idx_cluster_powerlaw ON {{table_name}}(cluster_powerlaw);
