name: Cleanup Packages

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

# Additional permissions required: enable "Admin" access in Package Settings > Manage Actions Access.
permissions:
  packages: write

jobs:
  cleanup:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore-versions: '^latest|main$'
          min-versions-to-keep: 10
          delete-only-untagged-versions: true
