name: lints

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive
  FORCE_COLOR: "1"
  PYTHONUNBUFFERED: "1"

jobs:
  linting:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: astral-sh/setup-uv@v6

      - name: Run ruff
        run: uv run ruff check --output-format=github .

      - name: Run mypy
        run: uv run mypy src
