name: Release Docker Image

on:
  workflow_run:
    workflows: [ "tests" ]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and release'
        required: true
        type: string
        default: 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-tests:
    runs-on: ubuntu-22.04
    if: |
      (github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'workflow_dispatch'
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_run=true" | tee -a $GITHUB_OUTPUT
          elif [[ "${{ github.event.workflow }}" == "tests" ]]; then
            echo "should_run=true" | tee -a $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: [ check-tests ]
    if: |
      github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') ||
      needs.check-tests.outputs.should_run == 'true'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,amd64'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
